[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
counter = "0.5.2"
itertools = "0.10.1"
num = "0.4.0"
regex = "1.5.4"
sscanf = "0.1.3"
